-- Create ROOMS table
CREATE TABLE ROOMS (
    ROOM_ID NUMBER PRIMARY KEY,
    ROOM_TYPE VARCHAR2(50),
    PRICE NUMBER(10,2),
    STATUS VARCHAR2(20) CHECK (STATUS IN ('Available', 'Booked'))
);

-- Insert sample rooms
INSERT INTO ROOMS VALUES (1, 'Deluxe', 150.00, 'Available');
INSERT INTO ROOMS VALUES (2, 'Standard', 100.00, 'Available');

-- Create RESERVATIONS table
CREATE TABLE RESERVATIONS (
    RESERVATION_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100),
    CONTACT_INFO VARCHAR2(100),
    ROOM_ID NUMBER,
    CHECK_IN_DATE DATE,
    CHECK_OUT_DATE DATE,
    FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
);

-- Sample reservation
INSERT INTO RESERVATIONS VALUES (1, 'John Doe', 'john@example.com', 1, TO_DATE('2025-04-01', 'YYYY-MM-DD'), TO_DATE('2025-04-05', 'YYYY-MM-DD'));
